config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root "home#index"
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :confirmable, :trackable, :lockable

  strip_attributes only: %i[first_name last_name email], collapse_spaces: true

  validates :first_name, :last_name, :email, presence: true, length: { maximum: 100 }
  validates :admin, inclusion: { in: [true, false] }

  def full_name
    "#{first_name} #{last_name}"
  end

  def initial
    "#{first_name[0].upcase}#{last_name[0].upcase}"
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_user!, :authenticate_admin

  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  def authenticate_admin
    return if current_user.admin?

    redirect_to root_path, flash: { danger: t("unauthorized_access") }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = t("page_title")

    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def flash_message_prefix(message_type)
    case message_type
    when "success" then t("alert_prefix.success")
    when "info"    then t("alert_prefix.info")
    when "warning" then t("alert_prefix.warning")
    when "danger"  then t("alert_prefix.danger")
    else ""
    end
  end

  def message_type(type)
    case type
    when "notice" then t("message_type.notice")
    when "alert"  then t("message_type.alert")
    else type
    end
  end
end

app/views/admin/home/index.html.erb
<h3>This is admin dashboard.</h3>

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<h1>Welcome to Book Your Show..!!</h1>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= message_type(type) %> alert-dismissible fade show mb-3" role="alert">
    <strong><%= flash_message_prefix(message_type(type)) %></strong> <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <%= link_to "BookYourShow", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <% if current_user.admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Dashboard", admin_root_path, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle user-dropdown-link active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.initial %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <span class="dropdown-item disabled">Hi, <%= current_user.full_name %></span>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="//code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <%= render "layouts/flash_messages" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <% resource.errors.full_messages.each.with_index(1) do |msg, index| %>
      <p class="mb-0"><%= index %>. <%= msg %>.</p>
    <% end %>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<% if controller_name != "sessions" %>
  <p class="mb-1">Do you have an account? <%= link_to "Login", new_session_path(resource_name) %></p>
<% end %>

<% if devise_mapping.registerable? && controller_name != "registrations" %>
  <p class="mb-1">Don't you have an account? <%= link_to "Signup", new_registration_path(resource_name) %></p>
<% end %>

<% if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <p class="mb-1">Didn't receive confirmation email? <%= link_to "Click here", new_confirmation_path(resource_name) %></p>
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks" %>
  <p class="mb-1">Didn't receive unlock email? <%= link_to "Click here", new_unlock_path(resource_name) %></p>
<% end %>

<% if devise_mapping.omniauthable? %>
  <hr>

  <% resource_class.omniauth_providers.each do |provider| %>
    <p class="mb-1">Sign in with <%= link_to "#{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %></p>
  <% end %>
<% end %>